name: gurps_dice
description: A starting point for Dart libraries or applications.
version: 1.1.0
# homepage: https://www.example.com
author: Wilson, Marvin (jw9615) <jw9615@att.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  quiver: ^2.1.3
  dart_utils: 
    git: 
      url: https://github.com/mjeffw/dart_utils.git
    version: ^2.0.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  test_coverage: ^0.3.0
